# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.background.setStyleSheet("QLabel#background{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.736318 rgba(0, 80, 120, 255));\n"
"}")
        self.background.setText("")
        self.background.setObjectName("background")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(300, 140, 220, 190))
        self.logo.setStyleSheet("")
        self.logo.setObjectName("logo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(560, 140, 191, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chargePercentageBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.chargePercentageBar.setStyleSheet(" QProgressBar::chunk {\n"
"     background-color: #3add36;\n"
"     width: 1px;\n"
" }\n"
"\n"
" QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 0px;\n"
"     text-align: center;\n"
" }")
        self.chargePercentageBar.setProperty("value", 90)
        self.chargePercentageBar.setInvertedAppearance(False)
        self.chargePercentageBar.setObjectName("chargePercentageBar")
        self.horizontalLayout_3.addWidget(self.chargePercentageBar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.voltageLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voltageLabel.setFont(font)
        self.voltageLabel.setStyleSheet("")
        self.voltageLabel.setObjectName("voltageLabel")
        self.horizontalLayout_6.addWidget(self.voltageLabel)
        self.voltageText = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.voltageText.setFont(font)
        self.voltageText.setStyleSheet("color: rgb(255,255,255)")
        self.voltageText.setObjectName("voltageText")
        self.horizontalLayout_6.addWidget(self.voltageText)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.batteryTemperatureLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.batteryTemperatureLabel.setFont(font)
        self.batteryTemperatureLabel.setObjectName("batteryTemperatureLabel")
        self.horizontalLayout_4.addWidget(self.batteryTemperatureLabel)
        self.batteryTemperatureText = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batteryTemperatureText.setFont(font)
        self.batteryTemperatureText.setStyleSheet("color: rgb(255,255,255)")
        self.batteryTemperatureText.setObjectName("batteryTemperatureText")
        self.horizontalLayout_4.addWidget(self.batteryTemperatureText)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.milesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.milesLabel.setFont(font)
        self.milesLabel.setStyleSheet("color: white")
        self.milesLabel.setObjectName("milesLabel")
        self.horizontalLayout_2.addWidget(self.milesLabel)
        self.milesText = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.milesText.setFont(font)
        self.milesText.setStyleSheet("color: white")
        self.milesText.setObjectName("milesText")
        self.horizontalLayout_2.addWidget(self.milesText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(270, 390, 291, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.pLabel.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.pLabel.setObjectName("pLabel")
        self.horizontalLayout_5.addWidget(self.pLabel)
        self.rLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.rLabel.setObjectName("rLabel")
        self.horizontalLayout_5.addWidget(self.rLabel)
        self.nLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.nLabel.setObjectName("nLabel")
        self.horizontalLayout_5.addWidget(self.nLabel)
        self.dLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.dLabel.setObjectName("dLabel")
        self.horizontalLayout_5.addWidget(self.dLabel)
        self.speedometer = QtWidgets.QLCDNumber(self.centralwidget)
        self.speedometer.setGeometry(QtCore.QRect(60, 150, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.speedometer.setFont(font)
        self.speedometer.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.speedometer.setStyleSheet("color: white;\n"
"background-color: rgba(255,255,255,0)")
        self.speedometer.setSmallDecimalPoint(False)
        self.speedometer.setDigitCount(3)
        self.speedometer.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.speedometer.setProperty("intValue", 50)
        self.speedometer.setObjectName("speedometer")
        self.mphLabel = QtWidgets.QLabel(self.centralwidget)
        self.mphLabel.setGeometry(QtCore.QRect(130, 280, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mphLabel.setFont(font)
        self.mphLabel.setStyleSheet("font-size: 20;\n"
"color:white;")
        self.mphLabel.setObjectName("mphLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 10, 401, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftArrow = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.leftArrow.setObjectName("leftArrow")
        self.horizontalLayout.addWidget(self.leftArrow)
        self.rightArrow = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.rightArrow.setObjectName("rightArrow")
        self.horizontalLayout.addWidget(self.rightArrow)
        self.shutdownButton = QtWidgets.QPushButton(self.centralwidget)
        self.shutdownButton.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.shutdownButton.setStyleSheet("QPushButton{\n"
"    border-image: url(:/img/shutdown);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/img/shutdownRed);\n"
"}")
        self.shutdownButton.setText("")
        self.shutdownButton.setObjectName("shutdownButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 400, 81, 71))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/img/logo\"width=\"220\" height=\"190\"/></p></body></html>"))
        self.voltageLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Voltage:</span></p></body></html>"))
        self.voltageText.setText(_translate("MainWindow", "300 V"))
        self.batteryTemperatureLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Battery temp:</span></p></body></html>"))
        self.batteryTemperatureText.setText(_translate("MainWindow", "300 F"))
        self.milesLabel.setText(_translate("MainWindow", "<html><head/><body><p>Miles range:</p></body></html>"))
        self.milesText.setText(_translate("MainWindow", "100 mi"))
        self.pLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">P</span></p></body></html>"))
        self.rLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">R</span></p></body></html>"))
        self.nLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">N</span></p></body></html>"))
        self.dLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">D</span></p></body></html>"))
        self.mphLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">MPH</span></p></body></html>"))
        self.leftArrow.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/img/leftArrow\"width=\"150\" height=\"100\"/></p></body></html>"))
        self.rightArrow.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/img/rightArrow\"width=\"150\" height=\"100\"/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/img/warning\"/></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
